package java_lox;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static java_lox.Token_Type.*;

public class Scanner {
    private final String source; //* this is the code that will be scanned
    private final List<Token> tokens = new ArrayList<>(); //* this is for the tokens generated by the scanner
    private int start = 0; //desc this is the index of the first character in the lexeme being scanned
    private int current = 0; //desc this is the index of the character being considered
    private int line = 1; //desc this provides the tokens' line no.s

    //gist this is the constructor for Scanner instances
    Scanner(String source) {
        this.source = source;}
    
    //gist this turns the whole code into tokens
    List<Token> scanTokens() {
        while (!isAtEnd()) {
            start = current;
            scanToken();}
        
        tokens.add(new Token(EOF, "", null, line));
        return tokens;}
    
    //gist this is to know if all the characters in the code have been scanned
    private boolean isAtEnd() {
        return current >= source.length();}
}
